# Generated by Django 5.0.8 on 2024-08-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=250, null=True)),
                ("email", models.CharField(max_length=255, null=True)),
                ("phone", models.PositiveIntegerField(null=True)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=1000, null=True, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Customer",
            },
        ),
    ]
