# Generated by Django 5.0.8 on 2024-08-17 10:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_report_treatmentlist_information_skincareinquiry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                null=True,
                populate_from="f{full_name}-{phone}",
            ),
        ),
    ]
